development: &development
  adapter: mysql2
  encoding: utf8
  database: canary_development
  pool: 5
  reconnect: true
  username: root
  password: admin123*

test:
  <<: *development
  database: canary_test
